config/routes.rb
DRIBatchIngest::Engine.routes.draw do

  get '/', to: "ingest#new"

  get 'batch', to: 'ingest#new', as: :new_batch
  get 'batch/:id', to: 'ingest#show', as: :batch
  post 'batch', to: 'ingest#create', as: :batch_ingest
  put 'batch/:id', to: 'ingest#update', as: :update_batch  

  get 'batch/:id/media/:media_id', to: 'media_objects#show', as: :media_object

  get 'ingests', to: 'user_ingests#index', as: :ingests

  put 'media/:id/files/:file_id', to: 'master_files#update'
      
  mount BrowseEverything::Engine => '/browse'
end

app/models/dri_batch_ingest/ingest_batch.rb
# frozen_string_literal: true
module DRIBatchIngest
  class IngestBatch < ActiveRecord::Base
    belongs_to :user_ingest, class_name: 'DRIBatchIngest::UserIngest'
    has_many :media_objects, class_name: 'DRIBatchIngest::MediaObject'

    def finished?
      media_objects.all?(&:finished_processing?)
    end

    def finished_at
      media_objects.empty? ? '-' : media_objects.order(:created_at).last.finished_at
    end
  end
end

app/models/dri_batch_ingest/master_file.rb
# frozen_string_literal: true
module DRIBatchIngest
  class MasterFile < ActiveRecord::Base
    belongs_to :media_object, class_name: 'DRIBatchIngest::MediaObject'

    END_STATES = %w[CANCELLED COMPLETED FAILED].freeze

    scope :metadata, -> { find_by(metadata: true) }

    def metadata?
      metadata == true
    end

    def preservation?
      preservation == true
    end

    def process(file = nil)
      raise "MasterFile is already being processed" if status_code.present? && !finished_processing?
    end

    def status?(value)
      status_code == value
    end

    def failed?
      status?('FAILED')
    end

    def succeeded?
      status?('COMPLETED')
    end

    def finished_processing?
      END_STATES.include?(status_code)
    end
  end
end

app/models/dri_batch_ingest/media_object.rb
# frozen_string_literal: true
module DRIBatchIngest
  class MediaObject < ActiveRecord::Base
    belongs_to :ingest_batch, class_name: 'DRIBatchIngest::IngestBatch'
    has_many :parts, class_name: 'DRIBatchIngest::MasterFile'

    scope :status, lambda { |status|
      joins(:parts).where('dri_batch_ingest_master_files.status_code' => status).distinct
    }

    scope :pending, -> { joins(:parts).where('dri_batch_ingest_master_files.status_code' => 'PENDING').distinct }

    scope :excluding_failed, -> { where(['dri_batch_ingest_media_objects.id NOT IN (?)', DRIBatchIngest::MediaObject.status('FAILED').pluck(:id)]) if failed.any? }

    scope :failed, -> { DRIBatchIngest::MediaObject.status('FAILED') }

    scope :completed, -> { DRIBatchIngest::MediaObject.status('COMPLETED') }

    def destroy
      parts.each(&:destroy)
      parts.clear
      super
    end

    def metadata
      parts.all.metadata
    end

    def finished_processing?
      parts.all?(&:finished_processing?)
    end

    def finished_at
      parts.order(:updated_at).last.updated_at
    end

    def succeeded?
      parts.all?(&:succeeded?)
    end

    def failed?
      parts.any?(&:failed?)
    end
  end
end

app/models/dri_batch_ingest/user_ingest.rb
# frozen_string_literal: true
class DRIBatchIngest::UserIngest < ActiveRecord::Base
  belongs_to :user, class_name: 'UserGroup::User'

  has_many :batches, class_name: 'DRIBatchIngest::IngestBatch'
end

app/controllers/dri_batch_ingest/application_controller.rb
# frozen_string_literal: true
class DRIBatchIngest::ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery
end

app/controllers/dri_batch_ingest/ingest_controller.rb
# frozen_string_literal: true
require 'avalon/batch'
require 'dri_batch_ingest/processors/entry_processor'
require 'dri_batch_ingest/csv_creator'

class DRIBatchIngest::IngestController < ApplicationController
  before_action :authenticate_user!
  before_action :read_only, except: [:index, :show]

  include DRI::Renderers::Json

  def base_dir
    @base_dir || set_base_dir
  end

  def index; end

  def new
    @collections = user_collections
    @ingests = DRIBatchIngest::UserIngest.where(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per(5)
    @batches = user_batches

    begin
      Dir.chdir(base_dir) { @user_dirs = directory_hash('.')[:children] }
    rescue Errno::ENOENT
      @user_dirs = nil
    end
  end

  def show
    @batch = DRIBatchIngest::IngestBatch.find(params[:id])

    @media_objects = if params[:status]
                       @batch.media_objects.status(params[:status]).page(params[:page]).per(25)
                     else
                       @batch.media_objects.page(params[:page]).per(25)
                     end
  end

  def create
    collection = params[:collection_id]
    ingest = DRIBatchIngest::UserIngest.create(user_id: current_user.id)

    if params.dig(:type) == 'manifest'
      Resque.enqueue(DRIBatchIngest::ProcessManifest, ingest.id, collection, params['selected_files'], provider_tokens)
    else
      metadata_path = params[:metadata_path]
      asset_path = params[:asset_path]
      preservation_path = params[:preservation_path]

      Resque.enqueue(DRIBatchIngest::CreateManifest, ingest.id, base_dir, current_user.email, collection, metadata_path, asset_path, preservation_path)
    end

    redirect_to ingests_url(ingest)
  end

  def update
    @batch = DRIBatchIngest::IngestBatch.find(params[:id])

    media_object_ids = @batch.media_objects.status('FAILED').pluck(:id)
    Resque.enqueue(DRIBatchIngest::ProcessBatch, @batch.id, media_object_ids)

    redirect_to ingests_url
  end

  private

  def user_batches
    batches = {}

    @ingests.each do |i|
      next unless i.batches.first
      batch = i.batches.first

      batches[batch.id] = {
        total: batch.media_objects.count,
        pending: batch.media_objects.excluding_failed.pending.count,
        completed: batch.media_objects.status('COMPLETED').count,
        failed: batch.media_objects.status('FAILED').count
      }
    end

    batches
  end

  def user_collections
    # User should see any collections that they have manage or edit permissions for
    query = "(_query_:\"{!join from=id to=ancestor_id_ssim}manager_access_person_ssim:#{current_user.email}\" OR manager_access_person_ssim:#{current_user.email})"
    query += " OR (_query_:\"{!join from=id to=ancestor_id_ssim}edit_access_person_ssim:#{current_user.email}\" OR edit_access_person_ssim:#{current_user.email})"

    fq = ["+is_collection_ssi:true"]
    fq << "+isGovernedBy_ssim:#{params[:governing]}" if params[:governing].present?
    fq << "+has_model_ssim:\"DRI::QualifiedDublinCore\""

    solr_query = Solr::Query.new(query, 100, fq: fq)
    nested_hash(build_collection_entries(solr_query))
  end

  def build_collection_entries(solr_query)
    entries = []
    solr_query.each do |document|
      id = document.id
      title = document['title_tesim'].first
      parents = document['ancestor_id_ssim']

      entries << { id: id, type: 'folder', text: title, parent_id: parents.nil? ? nil : parents.first }
    end

    entries
  end

  def nested_hash(entries)
    nested_hash = Hash[entries.map { |e| [e[:id], e.merge(children: [])] }]
    nested_hash.each do |_id, item|
      parent = nested_hash[item[:parent_id]]
      parent[:children] << item if parent
    end
    nested_hash.select { |_id, item| item[:parent_id].nil? }.values
  end

  def directory_hash(path, name = nil, exclude = [])
    exclude.concat(['..', '.', '.git', '__MACOSX', '.DS_Store'])
    key = (name || path)
    data = { text: key, type: 'folder', data: { path: path } }
    data[:children] = []
    Dir.foreach(path) do |entry|
      next if exclude.include?(entry)
      full_path = path == '.' ? entry : File.join(path, entry)
      data[:children] << directory_hash(full_path, entry) if File.directory?(full_path)
    end

    data
  end

  def provider_tokens
    tokens = {}
    browser = BrowseEverything::Browser.new
    browser.providers.values.each do |p|
      tokens["#{p.key}_token"] = session["#{p.key}_token"] if session["#{p.key}_token"].present?
    end

    tokens
  end

  def set_base_dir
    url_options = BrowseEverything.config
    url_options['sandbox_file_system'][:current_user] = current_user.email if url_options['sandbox_file_system'].present?
    browser = BrowseEverything::Browser.new(url_options)
    browser.providers['sandbox_file_system'].home
  end
end

app/controllers/dri_batch_ingest/master_files_controller.rb
# frozen_string_literal: true
class DRIBatchIngest::MasterFilesController < ApplicationController
  before_action :authenticate_user_from_token!
  before_action :authenticate_user!

  def update
    if params[:master_file][:file_location].present?
      path = params[:master_file].delete(:file_location)
      location = path.start_with?('error:') ? path : "#{Settings.dri.endpoint.chomp('/')}/#{path}"
      params[:master_file][:file_location] = location
    end

    master_file = DRIBatchIngest::MasterFile.find(params[:file_id])
    master_file.update_attributes(update_params)
    master_file.save

    respond_to do |format|
      format.json { head status: :ok }
    end
  end

  private

  def update_params
    params.require(:master_file).permit(:status_code, :file_location)
  end
end

app/controllers/dri_batch_ingest/media_objects_controller.rb
# frozen_string_literal: true
require 'filesize'

class DRIBatchIngest::MediaObjectsController < ApplicationController
  before_action :authenticate_user_from_token!
  before_action :authenticate_user!

  def show
    @batch = DRIBatchIngest::IngestBatch.find(params[:id])
    @media_object = DRIBatchIngest::MediaObject.find(params[:media_id])

    @files = @media_object.parts.page params[:page]

    @file_info = {}
    @files.each do |f|
      info = {}
      ds = JSON.parse(f['download_spec'])
      info[:title] = ds['file_name']
      info[:size] = ::Filesize.from("#{f.file_size} B").pretty
      info[:url] = ds['url']
      @file_info[f.id] = info
    end
  end
end

app/controllers/dri_batch_ingest/user_ingests_controller.rb
# frozen_string_literal: true
class DRIBatchIngest::UserIngestsController < ApplicationController
  before_action :authenticate_user!

  def index
    @ingests = DRIBatchIngest::UserIngest.where(user_id: current_user.id).order(created_at: :desc).page(params[:page]).per(10)
    @batches = user_batches
  end

  def show; end

  private

  def user_batches
    batches = {}

    @ingests.each do |i|
      next unless i.batches.first
      batch = i.batches.first

      batches[batch.id] = {
        total: batch.media_objects.count,
        pending: batch.media_objects.excluding_failed.pending.count,
        completed: batch.media_objects.status('COMPLETED').count,
        failed: batch.media_objects.status('FAILED').count
      }
    end

    batches
  end
end

app/helpers/dri_batch_ingest/application_helper.rb
# frozen_string_literal: true
module DRIBatchIngest
  module ApplicationHelper
  end
end

app/views/dri_batch_ingest/ingest/_form_create.html.erb
  <div class="wizard" id="ingestWizard">
    <ul class="nav">
      <li>
        <a class="nav-link" href="#step-1">
          Collection
        </a>
      </li>
      <li>
        <a class="nav-link" href="#step-2">
          Metadata
        </a>
      </li>
      <li>
        <a class="nav-link" href="#step-3">
          Assets
        </a>
      </li>
      <li>
        <a class="nav-link" href="#step-4">
          Preservation Assets
        </a>
      </li>
    </ul>

    <div class="tab-content">
      <div id="step-1" class="tab-pane" role="tabpanel">
        <%= form_tag(batch_ingest_path, id: 'ingest_wizard_form', method: 'post') do %>
          <%= hidden_field_tag 'metadata_path' %>
          <%= hidden_field_tag 'asset_path' %>
          <%= hidden_field_tag 'preservation_path' %>
          <%= hidden_field_tag 'type', 'create' %>
          <%= hidden_field_tag 'collection_id' %>

          <h4>Collection for ingest</h4>
          <p>Select the collection to ingest to</p>
          <div class="form-group">
            <div id="collectionsSelectable">
            </div>
          </div>
      </div>

      <div id="step-2" class="tab-pane" role="tabpanel">
          <h4>Select metadata directory</h4>
          <p>This directory should contain the XML metadata files with the file extension <b>.xml</b></p>

          <div class="form-group">
            <div id="metadataSelectableFolder">
           </div>
          </div>
      </div>

      <div id="step-3" class="tab-pane" role="tabpanel">
            <h4>Select asset directory</h4>
            <p>Asset files for a given object should have the same base filename as the metadata file, for example, the metadata file myobject_1.xml
             corresponds to the asset file myobject_1.pdf. If you have more than one asset file for a given object then an underscore and sequence  number should be appended to the basename, for example:</br>
             <ul><li>myobject_1_001.tiff</li><li>myobject_1_002.tiff</li><li>myobject_1_003.pdf</li></ul>
             </br>
            </p>
            <div class="form-group">
              <div id="assetSelectableFolder">
              </div>
            </div>
      </div>

      <div id="step-4" class="tab-pane" role="tabpanel">
            <h4>Select preservation asset directory</h4>
            <p>Preservation files can be added to the object. These files will not have surrogates generated from them and will
              only be displayed to editors or users that have been granted permission.
            </p>
             <div class="form-group">
               <div id="preservationSelectableFolder">
               </div>
            </div>
      </div>

      <% end %> <!-- close form tag -->
    </div>

  <script>
    $(document).ready(function() {
      var folders = JSON.parse('<%= raw escape_javascript(@user_dirs.to_json) %>');
      var collections = JSON.parse('<%= raw escape_javascript(@collections.to_json) %>');

      $("#ingestWizard #collectionsSelectable").jstree({
        'core' : {
          'data' : collections,
          'multiple' : false
        }
      })

      $("#metadataSelectableFolder").jstree({
        'core' : {
          'data' : folders,
          'multiple' : false
        }
      })

      $("#assetSelectableFolder").jstree({
        'core' : {
          'data' : folders,
          'multiple' : false
        }
      })

      $("#preservationSelectableFolder").jstree({
        'core' : {
          'data' : folders,
          'multiple' : false
        }
      })
    });
  </script>

app/views/dri_batch_ingest/ingest/_form_manifest.html.erb
<div class="wizard" id="ingestManifestWizard">
  <ul class="nav">
    <li>
      <a href="#step-1" class="nav-link">
        Collection
      </a>
    </li>
    <li>
      <a href="#step-2" class="nav-link">
        Manifest
      </a>
    </li>
  </ul>

  <div class="tab-content">
    <div id="step-1" class="tab-pane" role="tabpanel">
      <%= form_tag(batch_ingest_path, id: 'manifest_form', method: 'post') do %>
        <%= hidden_field_tag 'type', 'manifest' %>
        <%= hidden_field_tag 'collection_id' %>

        <h4>Collection for ingest</h4>
        <p>Select the collection to ingest to</p>
        <div class="form-group">
          <div id="collectionsSelectable">
          </div>
        </div>
    </div>
    <div id="step-2" class="tab-pane" role="tabpanel">
        <h4>Select manifest from storage</h4>

        <%= button_tag("Browse", type: 'button', class: 'btn btn-large btn-success', id: "browse-btn",
          'data-toggle' => 'browse-everything', 'data-route' => browse_everything_engine.root_path,
          'data-target' => '#manifest_form' ) %>

        <p id="status">0 items selected</p>
    </div>
    <% end %>
  </div>
</div>

<script>
  $(document).ready(function() {
    var collections = JSON.parse('<%= raw escape_javascript(@collections.to_json) %>');
    $("#ingestManifestWizard #collectionsSelectable").jstree({
      'core' : {
        'data' : collections,
        'multiple' : false
      }
    });
  });
</script>

app/views/dri_batch_ingest/ingest/new.html.erb
<div class="dri_main_content_container">
<div>
  <h3>Current and previous ingests</h3>
</div>
<div>
  <%= render partial: 'dri_batch_ingest/user_ingests/user_ingests_table' %>
</div>

<div>
  <h3>Start new ingest</h3>
</div>

<div style="margin-bottom:10px">
  <% if @user_dirs.nil? %>
    <p><i class="fa fa-exclamation-triangle"></i> Your user directory could not be found in ingest storage.
       If you have not yet done so, please go to <a href='https://repository.dri.ie/cloud' target="_blank">repository.dri.ie/cloud</a>
       and sign in to create the storage area. Metadata and files must be uploaded to this area before starting the ingest here.
    </p>
  <% else %>
    <a class="btn btn-primary" href="#" id="create"><i class="fa fa-wrench"></i> Create ingest from files</a>
  <% end %>
</div>

<div id="ingest-wizard-container" class="ingest-wizard-container">
<div id="existing_manifest" style="display:none">
  <%= render partial: 'form_manifest' %>
</div>

<div id="create_manifest" style="display:none">
  <%= render partial: 'form_create' %>
</div>
</div>
</div>
<script>
$("#existing").click(function() {
  $("#create_manifest").hide();
  $("#existing_manifest").toggle();
});

$("#create").click(function() {
  $("#existing_manifest").hide();
  $("#create_manifest").toggle();
});
</script>

app/views/dri_batch_ingest/ingest/show.html.erb
<div id="dri_crumbtrail_nav_container_id">
  <ol class="breadcrumb">
    <li><%= link_to "Ingests", ingests_path %></li>
    <li>Objects</li>
  </ol>
</div>

<% if request.query_string.include?('FAILED') %>
  <%= form_for update_batch_path(@batch.id), method: 'put', html: { class: "form-inline"} do |f| %>
    <%= f.submit "Retry Failed", class: 'dri_button_grey' %>
  <% end %>
<% end %>

<%= paginate @media_objects %>

<table class="table">
  <thead>
  <tr>
    <th>Object</th>
    <th>Time</th>
    <th>Location</th>
    <th>Status</th>
  </tr>
</thead>
<tbody>
  <% @media_objects.each do |mo| %>
    <% if mo.finished_processing? %>
      <% if mo.succeeded? %>
        <% row_class = "success" %>
        <% status = "COMPLETED" %>
      <% else %>
        <% row_class = "danger" %>
        <% status = "FAILED" %>
      <% end %>
    <% else %>
      <% if mo.failed? %>
        <% row_class = "danger" %>
        <% status = "FAILED" %>
      <% else %>
        <% row_class = "info" %>
        <% status = "PENDING" %>
      <% end %>
    <% end %>
    <tr class="<%= row_class %>" style="cursor: pointer" onclick="document.location = '<%= media_object_path(@batch.id, mo.id) %>'">
    <td><%= mo.id %></td><td><%= mo.updated_at %></td><td><%= mo.parts.metadata.file_location %></td><td><%= status %></td>    
    </tr>
  <% end %>
</tbody>
</table>